services:
  wiimote:
    build:
      context: .
    image: wiimote-mvp:latest
    working_dir: /app
    stdin_open: true
    tty: true
  wiimote-hw:
    build:
      context: .
    image: wiimote-mvp:latest
    working_dir: /app
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    pid: host
    profiles:
      - linux-hw
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/input:/dev/input
      - /dev/uinput:/dev/uinput
